In [ ]:
pip install numpy

In [ ]:
pip install pandas

In [5]:
import numpy as np
import pandas as pd

In [12]:
array_01 = np.random.randint(0,100, size = 10)
print(f'Array aleatório:\n{array_01}')
print(f'Tipo de dado: {array_01.dtype}')

Array aleatório:
[12 70 96 64  8 87 50 91 30 18]
Tipo de dado: int32


In [16]:
matriz_02 = np.random.rand(5,5)
print(f'Matriz aleatória:\n{matriz_02}')
print(f'Valor mínimo: {matriz_02.min()}')
print(f'Valor máximo: {matriz_02.max()}')
print(f'Valor mediano: {matriz_02.mean()}')

Matriz aleatória:
[[0.00183185 0.68800609 0.51574523 0.30701919 0.01562049]
 [0.49886196 0.73985194 0.38068621 0.20616776 0.69089995]
 [0.18125305 0.61642301 0.12743323 0.67799908 0.44888125]
 [0.88133271 0.38214481 0.96166092 0.49471773 0.65357643]
 [0.4431777  0.5267111  0.75806379 0.83430137 0.71789962]]
Valor mínimo: 0.001831847409472065
Valor máximo: 0.9616609151942503
Valor mediano: 0.510010657546482


In [28]:
array_03 = ((np.random.rand(10))*10).astype(int)
print(array_03)

[3 5 2 6 7 3 1 5 6 8]


In [51]:
array_04 = (np.random.rand(3,3)*9).astype(int)
print(array_04)
array_04b = array_04
array_04b[1, :] = -1
for i in range (3):
    array_04[1,i] = -1

print(array_04)
print(array_04b)

[[6 4 8]
 [1 2 5]
 [3 8 1]]
[[ 6  4  8]
 [-1 -1 -1]
 [ 3  8  1]]
[[ 6  4  8]
 [-1 -1 -1]
 [ 3  8  1]]


In [48]:
base_df = {'Fruta':['Banana', 'Maçã', 'Pera'],'Preço':[7.9, 10.8, 11.9], 'Quantidade':[12,3,4]}
df = pd.DataFrame(base_df)
df

Fruta  Preço  Quantidade
0  Banana    7.9          12
1    Maçã   10.8           3
2    Pera   11.9           4